/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.ui;

import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ma.connexion.Connexion;
import ma.projet.beans.Devlopper;
import ma.projet.beans.Manager;
import ma.projet.service.DeveloperService;
import ma.projet.service.ManagerService;




public class ManagerForm extends javax.swing.JInternalFrame {
       
 
   
    private ManagerService ms;
    DefaultTableModel m;
    static int id = 0;
    public ManagerForm() {
        initComponents();
       
        ms=new ManagerService();
        m= (DefaultTableModel) developperTable.getModel();
       
        
        
    }
    
 public void loadManager(){
        m.setRowCount(0);
        for(Manager c: ms.getAll()){
            m.addRow(new Object[]{
            c.getId(),c.getNom(),c.getSalaire()});
        }}
     
     public void updateManager(Manager c){
         
         
     String req = "UPDATE client SET nom='" + nomTxt.getText() + "', salaire='" + salaireTxt.getText()  + "' WHERE id=" + c.getId();

        try {
          
           Statement st = Connexion.getConnection().createStatement();
           st.executeUpdate(req);
            
            if(st.executeUpdate(req) == 1)
                System.out.println("La modification a été réalisée avec succès.");
        } catch (SQLException ex) {
            System.out.println("Erreur de modifier d'un client:" +ex.getMessage());
        }
        
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nom = new javax.swing.JLabel();
        salaire = new javax.swing.JLabel();
        nomTxt = new javax.swing.JTextField();
        salaireTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        addDev = new javax.swing.JButton();
        deleteDev = new javax.swing.JButton();
        modifierMna = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        developperTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des clients"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des managers");
        setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nom.setText("Nom:");

        salaire.setText("Salaire");

        nomTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTxtActionPerformed(evt);
            }
        });

        salaireTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaireTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salaire)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(salaireTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nomTxt)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaireTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        addDev.setText("Ajouter");
        addDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDevActionPerformed(evt);
            }
        });

        deleteDev.setText("Supprimer");
        deleteDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDevActionPerformed(evt);
            }
        });

        modifierMna.setText("Modifier");
        modifierMna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierMnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(deleteDev, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(addDev, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(modifierMna, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(deleteDev)
                .addGap(31, 31, 31)
                .addComponent(modifierMna)
                .addGap(45, 45, 45))
        );

        developperTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Salaire"
            }
        ));
        developperTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                developperTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(developperTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTxtActionPerformed

    private void salaireTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaireTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaireTxtActionPerformed

    private void addDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDevActionPerformed
        // TODO add your handling code here:
        if (nomTxt.getText()==null || salaireTxt.getText()==null){
          
            JOptionPane.showMessageDialog(this, "Saiser les informations du nouveau developperu");
        }else{
        if(ms.create(new Manager(nomTxt.getText(),Double.parseDouble(salaireTxt.getText())))){
        JOptionPane.showMessageDialog(this, "Ajout effectué avec succès !");}
        loadManager();
        }
        
    }//GEN-LAST:event_addDevActionPerformed

    private void deleteDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDevActionPerformed
        // TODO add your handling code here:
      if (id == 0){
            JOptionPane.showMessageDialog(this, "Sélectioner l'objet a supprimer");}
      else{
     int reponse= JOptionPane.showConfirmDialog(this, "Vollez vous supprimer ce client?");

      if (reponse==0){
          ms.delete(ms.getById(id));
          loadManager();
      }
    }//GEN-LAST:event_deleteDevActionPerformed
    }
    private void modifierMnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierMnaActionPerformed
        // TODO add your handling code here:
        if (id == 0 || nomTxt.getText()==null || salaireTxt.getText()==null ){
            JOptionPane.showMessageDialog(this, "Veuillez choisir l'élément que vous souhaitez modifier et entrer les nouvelles informations!");}
        else{  int reponse= JOptionPane.showConfirmDialog(this, "Vollez vous modifier ce client?");
         Manager c1=ms.getById(id);
      if (reponse==0){
          updateManager(c1);
          loadManager();
           JOptionPane.showMessageDialog(this, "La modification a été réalisée avec succès.");
      }
        }
        //cs.update(new Devlopper(nomTxt.getText(),prenomTxt.getText(),dateChooser.getDate(),new Manager(serviceTxt.getText())));
    }//GEN-LAST:event_modifierMnaActionPerformed

    private void developperTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_developperTableMouseClicked
        // TODO add your handling code here:
        id = Integer.parseInt(m.getValueAt(developperTable.getSelectedRow(), 0).toString());

       
    }//GEN-LAST:event_developperTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDev;
    private javax.swing.JButton deleteDev;
    private javax.swing.JTable developperTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifierMna;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nomTxt;
    private javax.swing.JLabel salaire;
    private javax.swing.JTextField salaireTxt;
    // End of variables declaration//GEN-END:variables
}
